import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Content from '../components/content'
import Footer from '../components/footer'
import Navbar from '../components/navbar'




const Home: NextPage = () => {
  return (
    <div className="bg-[url('../public/nether-portal.gif')] bg-">
      <Head>
        <title>Loophole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="sticky top-0 z-50 blue">
        <Navbar />
      </div>
      <div className=' justify-between p-5 max-w-7xl mx-auto' >
      <Content />
      </div>

      <Footer />
    </div>
  )
}

export default Home
