import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Content from '../components/content'
import Footer from '../components/footer'
import Navbar from '../components/navbar'




const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Loophole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col h-screen justify-between">

      <div className="sticky top-0 z-50 blue">
        <Navbar />
      </div>
      <div className='h-full p-5 outline-dashed outline-cyan-700' >
      <Content />
      </div>

      
      <Footer />

      </div>
   
    </div>
  )
}

export default Home
